name: dotnet package

on: [push]

jobs:
  build:
    permissions:
      checks: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity minimal  -l:"trx;LogFileName=test-report.trx" --collect:"XPlat Code Coverage" --results-directory ./reports


      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()      # run this step even if previous step failed
        with:
          name: Tests Results           # Name of the check run which will be created
          path: reports/*.trx # Path to test results
          reporter: dotnet-trx          # Format of test results
    
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: reports/**/coverage.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Install newman
        run: |
          npm install -g newman

      - name: Run Postman collection
        run: |
          dotnet run --project MoodTrackerAPI;
          newman run ./MoodTrackerApi.postman_collection.json -r cli --environment MoodTrackerAPI.postman_environment.json
      # - name: Run newman Tests
      #   uses: matt-ball/newman-action@master
      #   with:
      #     collection: 'MoodTrackerAPi Integration Tests.postman_collection.json'
      #     environment: MoodTrackerAPI.postman_environment.json